### PR TITLE
yespower-0.5

### PR DESCRIPTION
**Pull request by cryptozeny**
Hi bitzenyPlus devs,

Version name is `z3.0.0`

The changes in this updates are:
 * a) add `yespower 0.5`: 100% compatible with previous version of yescrypt and sync speed up
 * b) prepare HF with `yespower 1.0`: not HF yet
 * c) applying solardiz's advice

Please review. Thanks!

*****
@solardiz helped me. thanks a lot!

https://github.com/cryptozeny/bitzeny/commit/ea21675aab1b507de0815ab61202b50aa15c469e#comments

### CODE REVIEW

**Comment by hitobb** [comment]
Great!

This is the first release as BitZeny Plus, so you should change to version name is z3.0.0.
This code is so important as to change the major version.

**Comment by Lesmiscore** [comment]
Evidence for compatibility about block by @cryptozeny : https://test-insight.bitzeny.jp/block/00002f6d51900381209b2ed9478d03d4e7ca0044a591845c5b97ff8e2a2eb1be

**Comment by solardiz** [comment]
@cryptozeny You're still not checking the return value. Instead, you now have `yespower_hash` return `int`, but then ignore its return value by having the prototype use `void` and consequently having the callers ignore this return value. Now that this is not just a miner, such sloppy code is actually dangerous. You must fix it before merging. The easiest way to fix this is to check the return value from `yespower_tls` and `abort()` on non-zero while inside `yespower_hash`. And have its return type as `void`.

Also, ideally you should move your `yespower.c` wrapper to outside of the `yespower` directory (since it's not part of yespower itself) and list the yespower source files in `Makefile.am` instead of using `#include` on the `.c` files. But this isn't critical, your current approach just looks sloppy.

**Comment by solardiz** [comment]
> how to check the return value? could you give me the code?

I could, but it's literally 2 lines of C, and you got to have someone capable of that on the team. If you're not that person, then please ask within your team. Me providing you very basic advice on C programming isn't long-term sustainable for your project.

**Comment by cryptozeny** [comment]
@solardiz thanks so much your advice :+1: we will do our best to find the right code :smile: we should study your yespower further :sweat_smile: 

related question: *Cryply* also has the same problem you said? I referred to Cryply... :sob: 

https://github.com/cryply/cryply-wallet/blob/d974128611963e664232c1d24a01f9b284af7421/src/hash/yespower/yespower.c#L36

**Comment by solardiz** [comment]
This has nothing to do with yespower specifically. It's just basic C programming.

You can't tell from that file/line alone, but yes looking at:

https://github.com/cryply/cryply-wallet/blob/d974128611963e664232c1d24a01f9b284af7421/src/core.cpp#L218

@cryply also has this problem (missed yespower return value check). I've just e-mailed their developer. Thanks.

**Comment by cryptozeny** [comment]
@solardiz is it looks better than old one? :thinking: 
```c
// PR-2 (hittob)
void yespower_hash(const char *input, char *output){
    if (yespower_tls(input, 80, &yespower_bitzeny, (yespower_binary_t *) output) == 0){
        return;
    }
    else{
        abort();
    }
}
```

**Comment by solardiz** [comment]
@cryptozeny Now this is correct, albeit weird. You might want to simplify it so that you don't need the `else`.

**Comment by cryptozeny** [comment]
thanks so much! :heart: :100:

File: src/crypto/yespower-bitzeny.c [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+#include "yespower/insecure_memzero.h"
+#include "yespower/sha256.c"
+#include "yespower/sha256.h"
+#include "yespower/yespower.h"
+#include "yespower/yespower-opt.c"
+
+static const yespower_params_t yespower_0_5_bitzeny = {YESPOWER_0_5, 2048, 8, "Client Key", 10};
+
+// WARNING DO NOT USE THIS IN yespower_hash YET. For later HF to yespower 1.0
+// TODO Find HF solution using unixtime
```
Comment (cryptozeny) [inline src/crypto/yespower-bitzeny.c]: cryply team uses `unixtime`. is this a good way for HF solution? we need the method from `yesPower 0.5` to `1.0`.

https://github.com/cryply/cryply-wallet/blob/d974128611963e664232c1d24a01f9b284af7421/src/hash/yespower/yespower.c#L39

```c
static const yespower_params_t v1 = {YESPOWER_0_5, 4096, 16, "Client Key", 10};

static const yespower_params_t v2 = {YESPOWER_0_9, 2048, 32, NULL, 0};

int yespower_hash(const char *input, char *output)
{
    uint32_t time = le32dec(&input[68]);
    if (time > 1530403200) {
        return yespower_tls(input, 80, &v2, (yespower_binary_t *) output);
    } else {
        return yespower_tls(input, 80, &v1, (yespower_binary_t *) output);
    }
}
```

Comment (hitobb) [reply src/crypto/yespower-bitzeny.c]: This program specifies the date to change the algorithm.

BitZeny Plus has not agreed on the change time to YesPoWer 1.0.
Therefore this function is not necessary for bitzeny plus,now.

File: src/crypto/yespower-bitzeny.c [hunk 2]
```diff
@@ -0,0 +1,50 @@
+/*-
+ * Copyright 2009 Colin Percival
+ * Copyright 2013-2018 Alexander Peslyak
+ * Copyright 2018 bitzenyPlus Core Developers
```
Comment (cryptozeny) [inline src/crypto/yespower-bitzeny.c]: https://github.com/bitzenyPlus/BitZenyPlus/issues/1#issuecomment-409073031

```
Copyright 2018 bitzenyPlus Core Developers
```

this should be 

```
Copyright 2018 bitzenyPlus Developers
```

File: src/clientversion.cpp [hunk 3]
```diff
@@ -13,7 +13,7 @@
  * for both bitcoind and bitcoin-core, to make it harder for attackers to
  * target servers or GUI users specifically.
  */
-const std::string CLIENT_NAME("Satoshi");
+const std::string CLIENT_NAME("bitzenyPlus");
```
Comment (cryptozeny) [inline src/clientversion.cpp]: https://github.com/bitzenyPlus/BitZenyPlus/issues/5

do it later. its not urgent.

File: src/crypto/yespower-bitzeny.c (hunk 1 above)
Comment (cryptozeny) [reply src/crypto/yespower-bitzeny.c]: @hitobb you are right. we need more discussion about the HF. this code is not urgent for now. however i just wanted to hear solardiz's opinion about `HF method`

Comment (solardiz) [reply src/crypto/yespower-bitzeny.c]: I think basing the hard-fork on block height is safer, but once the network successfully gets significantly past this event it doesn't matter which method was used - there's supposed to be core code that disallows decreasing block timestamps. But I am no expert in this.

File: src/crypto/yespower-bitzeny.c (hunk 2 above)
Comment (solardiz) [reply src/crypto/yespower-bitzeny.c]: Looks like this file doesn't contain anything written by Colin or by me, so please drop our copyright statements from it.

File: src/crypto/yespower-bitzeny.c [hunk 4]
```diff
@@ -0,0 +1,50 @@
...
+#include "yespower/sha256.c"
+#include "yespower/sha256.h"
+#include "yespower/yespower.h"
+#include "yespower/yespower-opt.c"
+
+static const yespower_params_t yespower_0_5_bitzeny = {YESPOWER_0_5, 2048, 8, "Client Key", 10};
+
+// WARNING DO NOT USE THIS IN yespower_hash YET. For later HF to yespower 1.0
+// TODO Find HF solution using unixtime
+static const yespower_params_t yespower_1_0_bitzeny = {YESPOWER_1_0, 2048, 8, "Client Key", 10};
```
Comment (solardiz) [inline src/crypto/yespower-bitzeny.c]: For yespower 1.0, I recommend not using any personalization string (this is in the documentation, please read it). So instead of `"Client Key", 10` use `NULL, 0`.

File: src/crypto/yespower-bitzeny.c [hunk 5]
```diff
@@ -0,0 +1,50 @@
...
+
+// yespower 0.5 only
+void yespower_hash(const char *input, char *output){
+    if (yespower_tls(input, 80, &yespower_0_5_bitzeny, (yespower_binary_t *) output) == 0){
+        return;
+    }
+    abort();
```
Comment (solardiz) [inline src/crypto/yespower-bitzeny.c]: OK, let me simplify this for you:

```c
    if (yespower_tls(input, 80, &yespower_0_5_bitzeny, (yespower_binary_t *) output))
        abort();
```

File: src/crypto/yespower-bitzeny.c [hunk 6]
```diff
@@ -0,0 +1,50 @@
...
+ *
+ * This file was originally written by Colin Percival as part of the Tarsnap
+ * online backup system.
+ */
+
+#include "yespower/insecure_memzero.h"
+#include "yespower/sha256.c"
+#include "yespower/sha256.h"
+#include "yespower/yespower.h"
+#include "yespower/yespower-opt.c"
```
Comment (solardiz) [inline src/crypto/yespower-bitzeny.c]: It's not great that you still use this hack with including everything from one file, instead of using `Makefile.am` properly. This probably works OK, but it isn't how these files were meant to be used.

File: src/crypto/yespower-bitzeny.c (hunk 5 above)
Comment (cryptozeny) [reply src/crypto/yespower-bitzeny.c]: 😍 wonderful!

File: src/crypto/yespower-bitzeny.c (hunk 4 above)
Comment (cryptozeny) [reply src/crypto/yespower-bitzeny.c]: for 1.0. great to know! 😄

File: src/crypto/yespower-bitzeny.c (hunk 6 above)
Comment (cryptozeny) [reply src/crypto/yespower-bitzeny.c]: i already added it to `src/Makefile.am` but if i remove these lines from here, build is fail. i will try it again... :sob: 

https://github.com/cryptozeny/bitzeny/blob/a7b23752533d605c6744ff3cf9226ae8fcbee825/src/Makefile.am#L274

Comment (solardiz) [reply src/crypto/yespower-bitzeny.c]: You don't appear to understand the difference between `crypto_libbitcoin_crypto_a_SOURCES`
and `noinst_HEADERS`. In fact, it looks like some others editing this file previously didn't understand either.

Comment (solardiz) [reply src/crypto/yespower-bitzeny.c]: You probably only need these 3 (and no `.h` files) in `crypto_libbitcoin_crypto_a_SOURCES`:

```
  crypto/yespower/sha256.c \
  crypto/yespower/yespower-opt.c \
  crypto/yespower-bitzeny.c
```

And you probably don't need `noinst_HEADERS`, but I wouldn't vouch for that without testing.

File: src/crypto/yespower-bitzeny.c [hunk 7]
```diff
@@ -0,0 +1,50 @@
+/*-
+ * Copyright 2009 Colin Percival
+ * Copyright 2013-2018 Alexander Peslyak
```
Comment (solardiz) [inline src/crypto/yespower-bitzeny.c]: Please don't forget to drop these copyright statements from yespower-bitzeny.c.

File: src/crypto/yespower-bitzeny.c (hunk 1 above)
Comment (hitobb) [reply src/crypto/yespower-bitzeny.c]: >I think basing the hard-fork on block height is safer

I think so.
We should consider again when the hard fork is finalized. 
It is better that not to change now.

File: src/crypto/yespower-bitzeny.c (hunk 6 above)
Comment (cryptozeny) [reply src/crypto/yespower-bitzeny.c]: @solardiz 
i removed all `#include` from `/src/crypto/yespower-bitzeny.c` and added lines to `src/Makefile.am` but, it builds error...

ERR
```bash
crypto/yespower-bitzeny.c:38:55: error: ‘yespower_binary_t’ undeclared (first use in this function)
   if (yespower_tls(input, 80, &yespower_0_5_bitzeny, (yespower_binary_t *) 
                                                       ^
crypto/yespower-bitzeny.c:38:55: note: each undeclared identifier is reported only once for each function it appears in
crypto/yespower-bitzeny.c:38:74: error: expected expression before ‘)’ token
 spower_tls(input, 80, &yespower_0_5_bitzeny, (yespower_binary_t *) output))
```

:thinking:

Comment (cryptozeny) [reply src/crypto/yespower-bitzeny.c]: https://gist.github.com/cryptozeny/e690492ac36fb61357efb5a2ec353d43

Comment (solardiz) [reply src/crypto/yespower-bitzeny.c]: Of course, you do need the one line `#include "yespower/yespower.h"` in `yespower-bitzeny.c`.

You also mis-indented the `abort();` line. This doesn't cause any error, it's just bad style.

Comment (solardiz) [reply src/crypto/yespower-bitzeny.c]: You also need `#include <stdlib.h>` for `abort()` to be available.

File: src/crypto/yespower-bitzeny.c (hunk 7 above)
Comment (cryptozeny) [reply src/crypto/yespower-bitzeny.c]: removed :smile:

File: src/crypto/yespower-bitzeny.c (hunk 6 above)
Comment (cryptozeny) [reply src/crypto/yespower-bitzeny.c]: it seems works! thanks! :+1:

**Comment by cryptozeny** [comment]
@solardiz it builds OK on my machine(ubuntu16.04 x64 intel) and VPS(ubuntu16.04) and works also good. but *travis-ci* failed. he said:

```bash
crypto/yespower/sha256.c:32:30: fatal error: insecure_memzero.h: No such file or directory
 #include "insecure_memzero.h"
                              ^
compilation terminated.
make[2]: *** [crypto/yespower/libbitcoinconsensus_la-sha256.lo] Error 1
make[2]: Leaving directory `/home/travis/build/bitzenyPlus/BitZenyPlus/build/bitzeny-arm-linux-gnueabihf/src'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/home/travis/build/bitzenyPlus/BitZenyPlus/build/bitzeny-arm-linux-gnueabihf/src'
make: *** [install-recursive] Error 1
The command "make $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && make $GOAL V=1 ; false )" exited with 1.
``` 

https://travis-ci.org/bitzenyPlus/BitZenyPlus/jobs/410304053#L1835

do i need add `yespower/insecure_memzero.h` to `src/Makefile.am` ? it was a workaround for me...

File: src/crypto/yespower-bitzeny.c (hunk 1 above)
Comment (cryptozeny) [reply src/crypto/yespower-bitzeny.c]: i agree. not now. we need more discussion about this. it's very important thing to our future.

**Comment by solardiz** [comment]
> do i need add yespower/insecure_memzero.h to src/Makefile.am ? it was a workaround for me...

This isn't supposed to help.

I don't immediately know what the problem is, and I'm out of time. Please either debug this on your own or revert the changes to whatever revision worked for you.

**Comment by cryptozeny** [comment]
Its fine! :smiley: There was plenty of help. It was impossible without you. Thank you so much! :heart:

File: src/crypto/yespower-bitzeny.c [hunk 8]
```diff
@@ -32,9 +32,32 @@
...
+
+and so on for higher N keeping r=32.
+
+You may also set the personalization string to your liking, but that is
+not required (you can set its pointer to NULL and its length to 0).  Its
+support is provided mostly for compatibility with existing modifications
+of yescrypt 0.5.
+*/
+
+// solardiz recommended yespower 1.0 settings of at least N=2048 r=32 (8 MiB)
```
Comment (cryptozeny) [inline src/crypto/yespower-bitzeny.c:59]: add comment: solardiz's advice from

https://github.com/BitzenyCoreDevelopers/bitzeny/pull/43

File: src/crypto/yespower-bitzeny.c [hunk 9]
```diff
@@ -32,9 +32,32 @@
 static const yespower_params_t yespower_0_5_bitzeny = {YESPOWER_0_5, 2048, 8, "Client Key", 10};
 
 // WARNING DO NOT USE THIS IN yespower_hash YET. For later HF to yespower 1.0
-// TODO Find HF solution using unixtime
-// For 1.0 personalization string is not required. you can set its pointer to NULL and its length to 0.
-static const yespower_params_t yespower_1_0_bitzeny = {YESPOWER_1_0, 2048, 8, NULL, 0};
+// TODO Find HF solution using unixtime or blockheight(recommended)
+
+/*
+Parameter selection for yespower 1.0.
```
Comment (cryptozeny) [inline src/crypto/yespower-bitzeny.c]: add comment: parameter info from

https://github.com/cryptozeny/bitzeny/blob/1f7c0dd6d36e9ef456d3733fca7579ec0e86c2bc/src/crypto/yespower/README#L82

**Review by cryptozeny — COMMENTED** [review]
TEST PASSED

 * Mainnet: `verified`
 * Testnet: `verified` 
 * Mainnet Insight Blockexplorer `verified` http://198.13.49.191:3000/
 * Testnet Miningpool `verified` http://140.82.49.51:8080/   (front display is still old)
 * Mainnet Miningpool `verified` >> Thanks to `discord@ROZ - mofumofu.me#1977`    
 https://insight.bitzeny.jp/block/00000003b010b80167dbdf2aea1e1efb614a9d6d034e17000e1284bf262d7cf1

*****
ETC

Total time to sync wallet: about `24` hours
Import old `non-HD` wallet.dat tested

*****
TESTING

Testing *Mainnet*:
```
./src/qt/bitzeny-qt -debug=1 -addnode=198.13.49.191
```

Testing *Testnet*:
```
./src/qt/bitzeny-qt -debug=1 -addnode=140.82.49.51
```

Test Instruction:
https://github.com/bitzenyPlus/BitZenyPlus/wiki/%5Bdev-only%5D-testing-z3.0.x-yespower-0.5

*****

screenshot from 2018-08-01 18-08-52
debug window_106

screenshot from 2018-08-01 20-06-22
screenshot from 2018-08-01 20-06-10
screenshot from 2018-08-01 20-01-20

tested with @zinntikumugai 

Testnet Miningpool
```json
{
  "version": 3000000,
  "subversion": "/Satoshi:3.0.0/",
  "protocolversion": 70015,
  "localservices": "000000000000000d",
  "localrelay": true,
  "timeoffset": 0,
  "networkactive": true,
  "connections": 13,
  "relayfee": 0.00001000,
  "incrementalfee": 0.00001000,
  "localaddresses": [
    {
      "address": "140.82.49.51",
      "port": 19253,
      "score": 13
    }
  ]
  ...
}
```
2f454e51622385d4187f1a17faec0e70
screenshot from 2018-08-04 14-46-18
screenshot from 2018-08-04 14-46-45
screenshot from 2018-08-05 02-55-38

**Review by hitobb — APPROVED** [review]
LGTM

File: src/hash.h [hunk 10]
```diff
@@ -213,12 +213,12 @@ class CHashWriterYescrypt: public CHashWriter
     uint256 GetHash() {
         uint256 result;
         assert(buf.size() == 80);
```
Comment (shuichiro-makigaki) [inline src/hash.h]: This is an unnecessary line.
I heard that this line was for debugging, which was added by old BitZeny developers.

**Review by shuichiro-makigaki — CHANGES_REQUESTED** [review]

File: src/hash.h (hunk 10 above)
Comment (cryptozeny) [reply src/hash.h]: @shuichiro-makigaki 
Thank you for your review! :+1: 

I still do not understand why this should be removed. Could you explain it in more detail?

Comment (cryptozeny) [reply src/hash.h]: Could you tell me who added this? And I want to see the commit log.

Comment (cryptozeny) [reply src/hash.h]: The original `bitcoin 0.15` code was here. you may right.

```c
    uint256 GetHash() {
        uint256 result;
        ctx.Finalize((unsigned char*)&result);
        return result;
    }
```
https://github.com/bitcoin/bitcoin/blob/b6677651515534ed81b182467b62a5fd3f42d4b9/src/hash.h#L149

Comment (cryptozeny) [reply src/hash.h]: i asked to @fish-en

Comment (cryptozeny) [reply src/hash.h]: @shuichiro-makigaki Could you fix this file for us? I am no expert in this file...

Comment (shuichiro-makigaki) [reply src/hash.h]: Ah, sorry, i'm talking about l.215 only. `assert` line is not necessary.
I think one of BitZeny developers (may be original author) added this line for debugging.
Usually, an assertion is used only for debugging because it may cause an unexpected exit of the program.

Comment (cryptozeny) [reply src/hash.h]: @shuichiro-makigaki Thank you for your explanation. I will remove this line and test again.

Comment (cryptozeny) [reply src/hash.h]: it seems ok. i will update soon

File: src/hash.h [hunk 11]
```diff
@@ -195,30 +195,30 @@ class CHashVerifier : public CHashWriter
...
 
     void write(const char *pch, size_t size) {
         buf.insert(buf.end(), pch, pch + size);
     }
 
     uint256 GetHash() {
         uint256 result;
-        assert(buf.size() == 80);
-        yescrypt_hash((const char*)buf.data(), (char*)&result);
+        // assert(buf.size() == 80);   // TODO: shuichiro-makigaki said this line is only for debugging and it may cause an unexpected exit of the program.
```
Comment (shuichiro-makigaki) [inline src/hash.h]: This should be removed, I think, instead of commented out.

**Review by shuichiro-makigaki — CHANGES_REQUESTED** [review]

**Review by shuichiro-makigaki — APPROVED** [review]
bbbbb

**Comment by cryptozeny** [comment]
finally merged 😊

File: src/crypto/yespower-bitzeny.c (hunk 6 above)
Comment (cryptozeny) [reply src/crypto/yespower-bitzeny.c]: @solardiz 

I got this error when building. gcc cannot find the file...
```bash
crypto/yespower-1.0.0/yespower-opt.c:103:31: fatal error: yespower-platform.c: No such file or directory
compilation terminated.
```

adding to `noinst_HEADERS` was a workaround. but you said it's not good.
```
noinst_HEADERS = crypto/yespower-1.0.0/yespower-platform.c
```

I see this line and is this a better fix? :thinking: or do you have any better linker solution?

`<crypto/yespower-1.0.0/yespower-opt.c>`
```diff
-- #include "yespower-platform.c" 
++ #include <crypto/yespower-1.0.0/yespower-platform.c>
```

Comment (cryptozeny) [reply src/crypto/yespower-bitzeny.c]: detailed error TRAVIS-CI said...

```bash
/bin/bash ../libtool  --tag=CC   --mode=compile /home/travis/build/cryptozeny/sugarchain-v0.16.3/depends/x86_64-unknown-linux-gnu/share/../native/bin/ccache gcc -m64 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I./obj -I./secp256k1/include -DBUILD_BITCOIN_INTERNAL -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -I/home/travis/build/cryptozeny/sugarchain-v0.16.3/depends/x86_64-unknown-linux-gnu/share/../include/ -DDEBUG_LOCKORDER -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS  -pipe -O1  -c -o crypto/yespower-1.0.0/libbitcoinconsensus_la-yespower-opt.lo `test -f 'crypto/yespower-1.0.0/yespower-opt.c' || echo './'`crypto/yespower-1.0.0/yespower-opt.c
libtool: compile:  /home/travis/build/cryptozeny/sugarchain-v0.16.3/depends/x86_64-unknown-linux-gnu/share/../native/bin/ccache gcc -m64 -DHAVE_CONFIG_H -I. -I../src/config -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I./obj -I./secp256k1/include -DBUILD_BITCOIN_INTERNAL -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -I/home/travis/build/cryptozeny/sugarchain-v0.16.3/depends/x86_64-unknown-linux-gnu/share/../include/ -DDEBUG_LOCKORDER -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -pipe -O1 -c crypto/yespower-1.0.0/yespower-opt.c  -fPIC -DPIC -o crypto/yespower-1.0.0/.libs/libbitcoinconsensus_la-yespower-opt.o
crypto/yespower-1.0.0/yespower-opt.c:57:2: warning: #warning "Note: AVX and XOP are not enabled.  That's OK." [-Wcpp]
 #warning "Note: AVX and XOP are not enabled.  That's OK."
  ^
crypto/yespower-1.0.0/yespower-opt.c:103:31: fatal error: yespower-platform.c: No such file or directory
compilation terminated.
```

Comment (cryptozeny) [reply src/crypto/yespower-bitzeny.c]: I fixed it with `CFLAGS`
```bash
YESPOWER_PATH=$TRAVIS_BUILD_DIR/src/crypto/yespower-1.0.0
export CFLAGS=-I$YESPOWER_PATH
```

no errors on linux
